<?php
$data = $block->getMovie()->getData();
$countMovie = count($data);
?>
<style>
    #title {
        text-align: center;
        color: green;
        text-transform: uppercase;
        border: solid blue;
        padding: 15px;
        background: black;
    }
</style>

<table border="3px" cellspacing="0px">
    <h1 id="title"><?= __("There are %1 films being released", $countMovie); ?></h1>
    <tr>
        <th><?= __("Movie name"); ?></th>
        <th><?= __("Description"); ?></th>
        <th><?= __("Rating"); ?></th>
        <th><?= __("Director name"); ?></th>
        <th><?= __("Actors name"); ?></th>
    </tr>
    <?php foreach ($data as $movie) { ?>
        <tr>
            <td><?= $movie['name_movie']; ?></td>
            <td><?= $movie['description'] ?></td>
            <td><?= $movie['rating'] ?></td>
            <td><?= $movie['name_dir']; ?></td>
            <td>
                <?php $actors = $block->getActor($movie['movie_id'])->getData(); ?>

                <?php if (count($actors) == 0) { ?>
                    <p style="color: red;"><?= __("The movie has no actors") ?></p>
                <?php } else { ?>
                    <?php foreach ($actors as $actor) { ?>
                        <p><?= $actor['name']; ?></p>
                    <?php } ?>
                <?php } ?>
            </td>
        </tr>

    <?php } ?>

</table>
